version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
    - ./:/app/
    command: yarn watch
  backend:
    build: .
    volumes:
    - ./:/app/
    ports:
    - "3000:3000"
    command: sh entrypoint.sh