default: &default
  page_size: 20
  default_user_setting:
    selectedTagIds: []
    postTagIds: []
  post:
    smallPostMaxLetters: 100
    postMaxLetters: 200


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default